@startuml
' left to right direction
title BlackJackモデリング

hide empty circle
hide empty members

rectangle オブジェクト図 {
  rectangle クライアント {
    class シュミレーター
    note right: 1万回
  }

  rectangle システム {
    class ブラックジャック
    class ディーラー
    class プレイヤー
    class デッキ
    class 手札
    class カード
    note top: ・数値とスートを持っている\n・Aは1 or 11 として計算する
    class hit
    note bottom: '合計点数が15以下'
    class stay
    note right: '合計点数が16以上'
    class 合計数値
    class 比較
    note top: '両プレイヤーがstayしたら'
    class 勝敗

    class 1枚手札に配る
    note bottom of 1枚手札に配る
      ・ゲーム開始時は2回配る
        ・そのうち1枚はAを配る
      ・プレイヤーがhitした時
    endnote
    class ゲーム開始
  }
  シュミレーター -- ブラックジャック
  ブラックジャック ... ゲーム開始
  ブラックジャック -down- ディーラー
  ブラックジャック -down- プレイヤー

  ゲーム開始 -- 1枚手札に配る
  ゲーム開始 -- 比較

  比較 -- 勝敗
  比較 -- 合計数値

  プレイヤー -- 手札
  プレイヤー -- hit
  プレイヤー -- stay

  ディーラー -- デッキ
  ディーラー -- 1枚手札に配る
  1枚手札に配る -- プレイヤー

  カード -- 手札
  カード -- デッキ
}

@enduml
